# netlify.toml

[build]
  publish = "."          # Your CMS index.html lives in the admin folder
  functions = "netlify/functions"  # Folder for serverless functions like auth.js
  command = ""              # No build command if using plain HTML/CSS/JS

# Redirect all Netlify Function calls to the functions folder
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Optional: Redirect /admin to CMS index.html
[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
  force = true
