backend:
  name: auth0
  auth_type: /api/auth   # serverless function handles the login securely
  app_id: CMS_AUTH_APP   # optional identifier, can be anything

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

publish_mode: editorial_workflow

collections:
  # 🏠 Home - pulls Events & News
  - name: "home"
    label: "Homepage"
    files:
      - label: "Events"
        name: "events"
        file: "data/events.json"
        fields:
          - label: "Events"
            name: "events"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Time", name: "time", widget: "string" }
              - { label: "Date", name: "date", widget: "string" }
              - { label: "Location", name: "location", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }

      - label: "News"
        name: "news"
        file: "data/news.json"
        fields:
          - label: "News"
            name: "news"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Summary", name: "summary", widget: "text" }
              - { label: "Date", name: "date", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Link", name: "link", widget: "string", required: false }

  # 📖 About Page
  - name: "about"
    label: "About Page"
    file: "data/about.json"
    fields:
      - { label: "Intro Title", name: "introTitle", widget: "string" }
      - { label: "Intro Text", name: "introText", widget: "text" }
      - { label: "Mission", name: "mission", widget: "text" }
      - { label: "Vision", name: "vision", widget: "text" }
      - label: "Values"
        name: "values"
        widget: "list"
        fields:
          - { label: "Quote", name: "quote", widget: "text" }
      - label: "Board Section"
        name: "board"
        widget: "object"
        fields:
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Caption", name: "caption", widget: "string" }

  # 👥 Leadership Page (folder-based)
  - name: "leadership"
    label: "Leadership Team"
    folder: "data/leadership"
    create: true
    extension: "json"
    format: "json"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Role", name: "role", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }

  # 📅 Parsha Data
  - name: "parsha"
    label: "Parsha"
    file: "data/parsha.json"
    fields:
      - label: "Parsha List"
        name: "parsha"
        widget: "list"
        fields:
          - { label: "English Name", name: "englishName", widget: "string" }
          - { label: "Hebrew Name", name: "hebrewName", widget: "string" }
          - { label: "Book", name: "book", widget: "string" }
          - label: "Refs"
            name: "refs"
            widget: "list"
            field: { label: "Reference", name: "ref", widget: "string" }
          - { label: "Short Summary", name: "shortSummary", widget: "text" }

  # 📞 Contact / Footer
  - name: "contact"
    label: "Contact & Footer"
    file: "data/contact.json"
    fields:
      - { label: "Address", name: "address", widget: "string" }
      - { label: "Email", name: "email", widget: "string" }
      - { label: "Phone", name: "phone", widget: "string" }
      - label: "Social Links"
        name: "socials"
        widget: "list"
        fields:
          - { label: "Platform", name: "platform", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }
